language: node_js
node_js:
  - "10.9.0"

script:
  - npm run build
  - npm run coverage

before_install:
  - npm i -g babel-preset-env mocha supertest node-dev babel-cli rimraf coveralls istanbul
  
after_script:
  - ./node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info  && npm run clear