language: node_js
node_js:
  - "10.9.0"

script:
  - npm run test
  - npm run coverage

before_install:
  - npm i -g babel-preset-env mocha supertest chai babel-cli rimraf coveralls istanbul

after_script:
  - ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js